# ReplicaCount sets up the number of replicas.
replicaCount: 1

# NameOverride customizes the chart name.
nameOverride: ""

# FullnameOverride customizes the full chart name
fullnameOverride: ""

# Image customizes the image name and tags.
image:
  repository: k8sland/go-dictionary-svc
  tag: 0.0.1
  pullPolicy: IfNotPresent

# Service alters the service type and ports.
service:
  portName: http
  type: ClusterIP
  port: 4000
  targetPort: http

# Resources specifies resource constraints in terms of cpu and memory.
resources:
  requests:
    cpu: 100m
    memory: 10Mi
  limits:
    cpu: 200m
    memory: 20Mi

# Probes specifies liveness and readiness probe attributes.
probes:
  liveness:
    delay: 5
    frequency: 10
    failures: 5
    successes: 1
    timeout: 15
  readiness:
    delay: 15
    frequency: 30

# NodeSelector binds this deployment to a node matching the labels.
nodeSelector: {}

# Affinity specifies how pods and nodes attracks or repells.
affinity: {}

# Toleration specifies on which nodes this pod will be allowed to run.
tolerations: []
