apiVersion: v1
kind: Pod
metadata:
  name: iconoflix1
spec:
  containers:
    - name: iconoflix
      image: quay.io/imhotep/iconoflix:mem
      ports:
        - name: api
          containerPort: 5000
