apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hangman
spec:
  rules:
  - host: trump.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: hangman1
          servicePort: http
  - host: halloween.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: hangman2
          servicePort: http