configs:
  api_url: http://192.168.64.83:30400

image:
  repository: quay.io/imhotepio/iconoguess
  tag: 0.0.1
  pullPolicy: Always

service:
  type: NodePort
  externalPort: 30401

iconoflix-api:
  image:
    tag: prom

  pg:
    user: fernand
    host: icx-db-postgresql
    secret: icx-db-postgresql
    pwd_key: postgres-password

  service:
    type: NodePort
    externalPort: 30400
